### ISSUE TITLE
Verify the status code on fetching sources

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ethpm-types#18]
We should verify the status code on this response before continuing, using `requests` or something

_Originally posted by @unparalleled-js in https://github.com/ApeWorX/ethpm-types/pull/17#discussion_r803109780_

p.s. this needs a lot more thought

**Comment by fubuloubu** [comment]
closed by #17

**Comment by unparalleled-js** [comment]
I see it checks `response.status_code == 200` but technically anything in the 200 range is valid.
Probably better to do `200 <= response.status_code < 300`.

**Comment by fubuloubu** [comment]
> I see it checks `response.status_code == 200` but technically anything in the 200 range is valid. Probably better to do `200 <= response.status_code < 300`.

I don't think anything other than 200 would be useful for our purposes:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses
