### ISSUE TITLE
Pydantic ValidationError for ContractType runtimeByteCode and deploymentBytesCode

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ethpm-types#36]
### Environment information

Latest ape

* Python Version: 3.9.7
* OS: macOS

### What went wrong?

When compiling `yearn-vaults` repo, I get an error about the value of `runtimeBytecode` not being valid hex.

the validation error comes from this line: https://github.com/ApeWorX/ethpm-types/blob/main/ethpm_types/utils.py#L17-L18

**Comment by unparalleled-js** [comment]
additional notes: the repo is very large and the values in this field are also very large

**Comment by unparalleled-js** [comment]
@fubuloubu

**Comment by unparalleled-js** [comment]
For some reason the two unexpected symbols that appear are `_` and `$`

**Comment by unparalleled-js** [comment]
I am guessing this has to do with the experimental ABI decoder

**Comment by unparalleled-js** [comment]
The ABI has sections surrounded by `$__` and `__$`

**Comment by fubuloubu** [comment]
Have I mentioned how much I hate Solidity?
https://docs.soliditylang.org/en/v0.8.14/using-the-compiler.html#library-linking

**Comment by unparalleled-js** [comment]
Closing and fixing in `ape-solidity`
